acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /user

acme_recommend:
    resource: "@AcmeRecommendBundle/Resources/config/routing.php"
    prefix:   /

# app/config/routing.yml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin