services:
    sonata.admin.post:
        class: Acme\RecommendBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
        arguments:
            - ~
            - Acme\RecommendBundle\Entity\Users
            - ~
        calls:
            - [ setTranslationDomain, [AcmeRecommendBundle]]